format_version = 1

[components]
pronk_commit = "8850480bb96aad992fc0314428011e4ef72e73b6"
castkms_commit = "108c53c3a891299b6b3057f820862c4ced46f1b9"
mutter_commit = "eecb32cf753c16dc6411783d35065a2280d503a8"
gnome_control_center_commit = "89b05432f8c49ebda981004b1113e614e1c82648"
wireplumber_commit = "bc4fa8f5e84806f86530c97cb35283eecc3ec081"
chromiacast_version = "0.3.0"

[interfaces]
castkms_capture_uapi_major = 0
castkms_capture_uapi_minor = 11
castkms_cec_uapi_major = 0
castkms_cec_uapi_minor = 1
pronk_dbus_api_major = 1
backend_protocol_major = 1
backend_protocol_minor = 0

[requirements]
rust = "1.83"
pronk_pipewire_api = "1.2.0"
tested_pipewire = "1.6.0"
wireplumber = "0.5.15"
