%global buildforkernels akmod
%global debug_package %{nil}

%global kmod_name castkms
%global commit 108c53c3a891299b6b3057f820862c4ced46f1b9

Name:           %{kmod_name}-kmod
Version:        0.11.0
Release:        5%{?dist}
Summary:        CastKMS virtual display kernel module

License:        GPL-2.0-only
URL:            https://github.com/pronkproject/castkms
Source0:        https://github.com/pronkproject/castkms/archive/%{commit}/%{kmod_name}-%{commit}.tar.gz

BuildRequires:  elfutils-libelf-devel
BuildRequires:  gcc
BuildRequires:  kmodtool
BuildRequires:  make
%{!?kernels:BuildRequires: kernel-devel}

%{expand:%(kmodtool --target %{_target_cpu} --repo fedora --kmodname %{kmod_name} %{?buildforkernels:--%{buildforkernels}} %{?kernels:--for-kernels "%{?kernels}"} 2>/dev/null | sed -e '/^Requires:[[:space:]]*kernel-uname-r[[:space:]]/{p;s/kernel-uname-r/kernel-modules-uname-r/;}') }

%description
CastKMS is an experimental DRM/KMS driver that provides disconnected virtual
monitor slots, grant-scoped frame capture, cursor metadata, HDMI audio, and
HDMI-CEC transport for network-display agents such as Pronk.

%package -n %{kmod_name}-kmod-common
Summary:        Common files for the CastKMS kernel module

%description -n %{kmod_name}-kmod-common
This package contains the license shared by CastKMS kernel module builds. It
also satisfies the common-package dependency generated by kmodtool for both
prebuilt kernel modules and akmods.


%prep
%{?kmodtool_check}
kmodtool --target %{_target_cpu} --repo fedora --kmodname %{kmod_name} \
  %{?buildforkernels:--%{buildforkernels}} \
  %{?kernels:--for-kernels "%{?kernels}"} 2>/dev/null

%autosetup -n %{kmod_name}-%{commit}


%build
for kernel_version in %{?kernel_versions}; do
  kernel_release=${kernel_version%%___*}
  kernel_build=${kernel_version##*___}
  make -C . \
    KDIR="$kernel_build" \
    MO="$PWD/_kmod_output_${kernel_release}" \
    %{?_smp_mflags} W=1
done


%install
for kernel_version in %{?kernel_versions}; do
  kernel_release=${kernel_version%%___*}
  install -D -m 0755 \
    _kmod_output_${kernel_release}/castkms.ko \
    %{buildroot}%{kmodinstdir_prefix}/${kernel_release}/%{kmodinstdir_postfix}/castkms.ko
done
%{?akmod_install}
install -D -m 0644 /dev/null \
  %{buildroot}%{_prefix}/lib/modules-load.d/castkms.conf
printf '%s\n' castkms > \
  %{buildroot}%{_prefix}/lib/modules-load.d/castkms.conf


%files -n %{kmod_name}-kmod-common
%license COPYING
%{_prefix}/lib/modules-load.d/castkms.conf


%changelog
* Sun Aug 30 2026 Ray Strode <rstrode@redhat.com> - 0.11.0-5
- Include the ALSA sequencer in dependency-aware boot images

* Sun Aug 30 2026 Ray Strode <rstrode@redhat.com> - 0.11.0-4
- Require supporting modules for the exact kmod kernel

* Sun Aug 30 2026 Ray Strode <rstrode@redhat.com> - 0.11.0-3
- Install the kernel modules required by CastKMS audio and CEC

* Sun Aug 30 2026 Ray Strode <rstrode@redhat.com> - 0.11.0-2
- Load CastKMS automatically at boot

* Sun Aug 30 2026 Ray Strode <rstrode@redhat.com> - 0.11.0-1
- Initial CastKMS akmod package
